import {Plate} from "@shared/interfaces/plate.interface";

export interface MenuState {
  menu: string;
  plates: Plate[];
  activateFilterSearchTerm: string;
  activateFilterSinTacc: boolean;
  activateFilterVegano: boolean;
  activateFilterByNames: string[];
  activateFilters: boolean;
  loading: boolean;
  error: string | null;
}

export const initialState: MenuState = {
  menu: '',
  plates: [
    {
      platoId: 1,
      nombre: 'Hamburguesa',
      categoria: 'Hamburguesa 1',
      precio: 2000,
      descripcion: 'Minced oysters can be made melted by whisking with gold tequila.',
      vegano: true,
      sinTACC: false,
      calificacion: 1,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 11,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 1,
      nombre: 'Hamburguesa',
      categoria: 'Hamburguesa 2',
      precio: 2000,
      descripcion: 'To the small oysters add watermelon, chickpeas, champaign and bitter rice.',
      vegano: false,
      sinTACC: true,
      calificacion: 2,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 5,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 1,
      nombre: 'Hamburguesa',
      categoria: 'Hamburguesa Vegana y sin tacc',
      precio: 2000,
      descripcion: 'Per guest prepare twelve peaces of worcestershire sauce with shreded butter for dessert.',
      vegano: true,
      sinTACC: true,
      calificacion: 3,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 0,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 2,
      nombre: 'Panini',
      categoria: 'Panini 1',
      precio: 2000,
      descripcion: 'Per guest prepare one package of kefir with sliced chicory for dessert.',
      vegano: true,
      sinTACC: false,
      calificacion: 4,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 0,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 2,
      nombre: 'Panini',
      categoria: 'Panini 2',
      precio: 2000,
      descripcion: 'Everyone just loves the pepperiness of tuna salad soakd with basil.',
      vegano: false,
      sinTACC: false,
      calificacion: 5,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 5,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 3,
      nombre: 'Panini',
      categoria: 'Panini 3',
      precio: 2000,
      descripcion: 'To the springy chicken add white bread, chicken breasts, joghurt and cold raspberries.',
      vegano: false,
      sinTACC: false,
      calificacion: 6,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 5,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 4,
      nombre: 'Panini',
      categoria: 'Panini 4',
      precio: 2000,
      descripcion: 'Toss each side of the cracker crumps with six and a half teaspoons of garlic.',
      vegano: false,
      sinTACC: true,
      calificacion: 7,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 5,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 5,
      nombre: 'Panini',
      categoria: 'Panini 5',
      precio: 2000,
      descripcion: 'Everyone just loves the pepperiness of tuna salad soakd with basil.',
      vegano: true,
      sinTACC: false,
      calificacion: 8,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 5,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 6,
      nombre: 'Panini',
      categoria: 'Panini 6',
      precio: 2000,
      descripcion: 'Everyone just loves the pepperiness of tuna salad soakd with basil.',
      vegano: true,
      sinTACC: false,
      calificacion: 9,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 5,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 7,
      nombre: 'Panini',
      categoria: 'Panini 7',
      precio: 2000,
      descripcion: 'Everyone just loves the pepperiness of tuna salad soakd with basil.',
      vegano: true,
      sinTACC: false,
      calificacion: 10,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 5,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 8,
      nombre: 'Panini',
      categoria: 'Panini 8',
      precio: 2000,
      descripcion: 'Everyone just loves the pepperiness of tuna salad soakd with basil.',
      vegano: true,
      sinTACC: false,
      calificacion: 5,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 5,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 9,
      nombre: 'Panini',
      categoria: 'Panini 9',
      precio: 2000,
      descripcion: 'Everyone just loves the pepperiness of tuna salad soakd with basil.',
      vegano: true,
      sinTACC: false,
      calificacion: 5,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 5,
      tipoPlato: 'Almuerzo y Cena',
    },
    {
      platoId: 3,
      nombre: 'Cafe',
      categoria: 'Expreso',
      precio: 4000,
      descripcion: 'To the melted white bread add pork shoulder, raspberries, beer and fluffy onion.',
      vegano: false,
      sinTACC: true,
      calificacion: 2,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 2,
      tipoPlato: 'Desayuno',
    },
    {
      platoId: 3,
      nombre: 'Cafe',
      categoria: 'Americano',
      precio: 4000,
      descripcion: 'Per guest prepare nine oz of lemon juice with boilled blueberries for dessert. .',
      vegano: false,
      sinTACC: false,
      calificacion: 2,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 2,
      tipoPlato: 'Desayuno',
    },
    {
      platoId: 4,
      nombre: 'Cafe',
      categoria: 'Submarino',
      precio: 4000,
      descripcion: 'To the tasty celery add raspberries, ginger, soy sauce and roasted turkey.',
      vegano: false,
      sinTACC: false,
      calificacion: 1,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 0,
      tipoPlato: 'Desayuno',
    },
    {
      platoId: 4,
      nombre: 'Te',
      categoria: 'Te Verde',
      precio: 4000,
      descripcion: 'To the tasty celery add raspberries, ginger, soy sauce and roasted turkey.',
      vegano: false,
      sinTACC: false,
      calificacion: 1,
      urlImagen: '/assets/img/plates/gourmet.jpg',
      stock: 0,
      tipoPlato: 'Desayuno',
    }
  ],
  activateFilters: false,
  activateFilterSearchTerm: '',
  activateFilterSinTacc: false,
  activateFilterVegano: false,
  activateFilterByNames: [],
  loading: false,
  error: null
};
